name: Animeflix prepare env
description: "Action que permitirá configurar el entorno de compilación de la app"

inputs:
  filepath-version:
    required: true
    description: "Ruta y archivo a utilizar para definir la versión"
    default: '.nvmrc'

runs:
  using: composite
  steps:
    - name: Prepare env
      uses: actions/setup-node@v4
      with:
        node-version-file: "${{ inputs.filepath-version }}"