name: CI Animeflix

on:
  push:

  pull_request:
    branches:
      - main
      
jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1
    
    - name: Prepare env
      uses: ./.github/actions/prepare
      with:
        filepath-version: '.nvmrc'
    
    - name: Install dependencies
      run: yarn clean:install
    
    #- name: Artifacts
      #uses: actions/upload-artifact@v4.4.3
      #with: 
        #name: artifact
        #path: node_modules

  build:
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1
    - name: Build app
      run: echo "Compilación exitosa"
