name: CI Animeflix

on:
  push:

  pull_request:
    branches:
      - main
      
jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: yarn clean:install

  build:
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
    - name: Build app
      run: echo "Compilación exitosa"
